import subprocess
import random
import time

search_terms_to_homepage = {
   "rokomari":" https://www.rokomari.com/book",
    "Python programming": "https://www.python.org",
    "OpenAI GPT-4": "https://www.openai.com",
    "Machine learning tutorials": "https://www.coursera.org/courses?query=machine%20learning",
    "Best coding practices": "https://www.codinghorror.com/blog/archives/000581.html",
    "Artificial intelligence news": "https://www.aitrends.com",
    "Data science projects": "https://www.kaggle.com",
    "How to use pandas in Python": "https://pandas.pydata.org",
    "Top programming languages 2024": "https://www.tiobe.com/tiobe-index",
    "Web development trends": "https://www.smashingmagazine.com",
    "Cloud computing services": "https://aws.amazon.com",
    "JavaScript frameworks": "https://reactjs.org",
    "Blockchain technology": "https://www.blockchain.com",
    "Cybersecurity tips": "https://www.csoonline.com",
    "DevOps practices": "https://aws.amazon.com/devops",
    "IoT innovations": "https://www.iotworldtoday.com",
    "Quantum computing basics": "https://quantum-computing.ibm.com",
    "Augmented reality applications": "https://www.magicleap.com",
    "Virtual reality gaming": "https://www.oculus.com",
    "Big data analytics": "https://hadoop.apache.org",
    "5G technology": "https://www.qualcomm.com/5g",
    "React.js tutorials": "https://reactjs.org/tutorial/tutorial.html",
    "Angular vs React": "https://angular.io",
    "Django for beginners": "https://www.djangoproject.com/start",
    "Flask vs Django": "https://flask.palletsprojects.com/en/2.0.x/",
    "API development best practices": "https://swagger.io",
    "RESTful services": "https://restfulapi.net",
    "GraphQL overview": "https://graphql.org",
    "Containerization with Docker": "https://www.docker.com",
    "Kubernetes for orchestration": "https://kubernetes.io",
    "Microservices architecture": "https://microservices.io",
    "Serverless computing": "https://aws.amazon.com/serverless",
    "Edge computing": "https://www.ibm.com/cloud/what-is-edge-computing",
    "CI/CD pipelines": "https://www.atlassian.com/continuous-delivery/ci-vs-ci-vs-cd",
    "Agile methodology": "https://www.agilealliance.org/agile101",
    "Scrum vs Kanban": "https://www.scrum.org",
    "Machine learning algorithms": "https://www.sciencedirect.com/topics/computer-science/machine-learning-algorithms",
    "Deep learning frameworks": "https://www.tensorflow.org",
    "NLP techniques": "https://spacy.io",
    "Computer vision projects": "https://opencv.org",
    "Reinforcement learning basics": "https://www.coursera.org/learn/machine-learning",
    "Supervised vs unsupervised learning": "https://www.geeksforgeeks.org/supervised-unsupervised-learning",
    "Python data structures": "https://docs.python.org/3/tutorial/datastructures.html",
    "Java programming tips": "https://www.oracle.com/java",
    "C++ for game development": "https://www.unrealengine.com",
    "Swift for iOS apps": "https://developer.apple.com/swift",
    "Kotlin for Android": "https://developer.android.com/kotlin",
    "Go programming language": "https://golang.org",
    "Rust for systems programming": "https://www.rust-lang.org",
    "Ruby on Rails": "https://rubyonrails.org",
    "PHP for web development": "https://www.php.net",
    "WordPress customization": "https://wordpress.org",
    "SEO strategies": "https://moz.com",
    "Digital marketing trends": "https://www.marketingprofs.com",
    "Content management systems": "https://www.drupal.org",
    "CRM tools": "https://www.salesforce.com",
    "ERP software": "https://www.sap.com",
    "Business intelligence": "https://powerbi.microsoft.com",
    "Data warehousing": "https://aws.amazon.com/redshift",
    "ETL processes": "https://talend.com",
    "Data lakes vs data warehouses": "https://www.cloudera.com",
    "Hadoop ecosystem": "https://hadoop.apache.org",
    "Spark for big data": "https://spark.apache.org",
    "Data visualization tools": "https://www.tableau.com",
    "Tableau vs Power BI": "https://www.gartner.com/reviews/market/analytics-business-intelligence-platforms/comparison/tableau-vs-microsoft",
    "Excel for data analysis": "https://support.microsoft.com/excel",
    "SQL vs NoSQL": "https://www.mongodb.com/nosql-explained/nosql-vs-sql",
    "MongoDB tutorials": "https://university.mongodb.com",
    "PostgreSQL features": "https://www.postgresql.org",
    "Oracle database management": "https://www.oracle.com/database",
    "Database indexing techniques": "https://www.sqlshack.com/sql-server-indexing-basics",
    "Networking basics": "https://www.cisco.com/c/en/us/solutions/enterprise-networks/what-is-networking.html",
    "OSI model": "https://www.cloudflare.com/learning/ddos/glossary/open-systems-interconnection-model-osi",
    "TCP/IP protocols": "https://www.techtarget.com/searchnetworking/definition/TCP-IP",
    "Firewall configuration": "https://www.checkpoint.com/cyber-hub/network-security/what-is-firewall",
    "VPN setup": "https://nordvpn.com",
    "Load balancing": "https://www.nginx.com/resources/glossary/load-balancing",
    "Network security measures": "https://www.sophos.com/en-us/network-security",
    "Penetration testing": "https://www.kali.org",
    "Ethical hacking": "https://www.eccouncil.org",
    "Wireless networking": "https://www.cisco.com/c/en/us/solutions/enterprise-networks/wireless.html",
    "Bluetooth technology": "https://www.bluetooth.com",
    "Zigbee protocol": "https://zigbeealliance.org",
    "LoRaWAN": "https://lora-alliance.org",
    "Network automation": "https://www.cisco.com/c/en/us/solutions/enterprise-networks/network-automation.html",
    "SDN and NFV": "https://www.sdxcentral.com/sdn-nfv",
    "Network function virtualization": "https://www.opennetworking.org",
    "Cloud storage solutions": "https://www.dropbox.com",
    "Hybrid cloud": "https://www.redhat.com/en/topics/cloud-computing/what-is-hybrid-cloud",
    "Public vs private cloud": "https://www.vmware.com/topics/glossary/content/public-cloud.html",
    "AWS vs Azure": "https://aws.amazon.com/what-is-aws",
    "Google Cloud Platform": "https://cloud.google.com",
    "DevSecOps practices": "https://www.redhat.com/en/topics/devops/what-is-devsecops",
    "Security automation": "https://www.automation.com/security",
    "Identity and access management": "https://www.okta.com",
    "Zero trust architecture": "https://www.paloaltonetworks.com/cyberpedia/what-is-zero-trust",
    "Blockchain in finance": "https://www.coindesk.com",
    "Smart contracts": "https://ethereum.org/en/smart-contracts",
    "NFTs explained": "https://www.theverge.com/22310188/nft-explainer-what-is-blockchain-crypto-art-faq",
    "Cryptocurrency trading": "https://www.coinbase.com",
    "Bitcoin mining": "https://www.bitcoin.com/get-started/how-bitcoin-mining-works",
    "Ethereum overview": "https://ethereum.org",
    "Stablecoins": "https://www.coinbase.com/learn/crypto-basics/what-are-stablecoins",
    "Decentralized finance": "https://www.defipulse.com",
    "Fintech innovations": "https://www.finextra.com",
    "Regtech solutions": "https://www.americanbanker.com",
    "Insurtech trends": "https://www.insurtechnews.com",
    "Healthtech advancements": "https://www.healthtechzone.com",
    "Medtech devices": "https://www.medicaldesignandoutsourcing.com",
    "Biotech breakthroughs": "https://www.bioworld.com",
    "AI in healthcare": "https://www.healthit.gov",
    "Telemedicine platforms": "https://www.teledoc.com",
    "Wearable technology": "https://www.wearable-technologies.com",
    "Fitness trackers": "https://www.fitbit.com",
    "Smart home devices": "https://www.cnet.com/smart-home",
    "Home automation": "https://www.smarthome.com",
    "Voice assistants": "https://assistant.google.com",
    "Smart speakers": "https://www.amazon.com/smart-speaker",
    "Connected cars": "https://www.tesla.com/autopilot",
    "Autonomous vehicles": "https://www.waymo.com",
    "Electric vehicles": "https://www.tesla.com",
    "Battery technology": "https://www.tesla.com/batteries",
    "Renewable energy sources": "https://www.irena.org",
    "Solar power": "https://www.seia.org/initiatives/about-solar-energy",
    "Wind energy": "https://www.awea.org",
    "Hydropower": "https://www.hydropower.org",
    "Geothermal energy": "https://www.geothermal-energy.org",
    "Energy storage solutions": "https://www.energy.gov/eere/energy-storage",
    "Smart grids": "https://www.smartgrid.gov",
    "Energy efficiency": "https://www.energystar.gov",
    "Sustainable living": "https://www.earthday.org",
    "Green technology": "https://www.greenbiz.com",
    "Environmental conservation": "https://www.worldwildlife.org",
    "Climate change solutions": "https://www.climatecentral.org",
    "Carbon footprint reduction": "https://www.nature.org/en-us/get-involved/how-to-help/consider-your-impact/reduce-carbon-footprint",
    "Waste management": "https://www.wm.com",
    "Recycling innovations": "https://www.recycleacrossamerica.org",
    "Circular economy": "https://www.ellenmacarthurfoundation.org",
    "Urban farming": "https://www.urbanfarming.org",
    "Smart cities": "https://www.smartcitiesworld.net",
    "IoT in agriculture": "https://www.iotworldtoday.com/iot-agriculture",
    "Precision farming": "https://www.precisionag.com",
    "Drones in agriculture": "https://www.precisionhawk.com",
    "Space exploration": "https://www.nasa.gov",
    "Satellite technology": "https://www.ses.com",
    "Mars colonization": "https://www.spacex.com/mars",
    "Lunar missions": "https://www.nasa.gov/specials/apollo50",
    "SpaceX innovations": "https://www.spacex.com",
    "NASA projects": "https://www.nasa.gov/missions",
    "Astronomy basics": "https://www.space.com",
    "Astrophysics": "https://www.aip.org",
    "Cosmology": "https://www.cosmos.esa.int",
    "Exoplanets": "https://exoplanets.nasa.gov",
    "Dark matter and dark energy": "https://www.darkenergy.com",
    "Black holes": "https://www.eventhorizontelescope.org",
    "Gravitational waves": "https://www.ligo.caltech.edu",
    "Quantum entanglement": "https://www.sciencemag.org",
    "Particle physics": "https://www.cern.ch",
    "Large Hadron Collider": "https://home.cern/science/accelerators/large-hadron-collider",
    "Standard model of particle physics": "https://home.cern/science/physics/standard-model",
    "String theory": "https://www.space.com/string-theory.html",
    "Multiverse hypothesis": "https://www.scientificamerican.com/article/are-parallel-universes-unscientific-nonsense",
    "Quantum computing applications": "https://www.ibm.com/quantum-computing",
    "Quantum cryptography": "https://www.idquantique.com",
    "Quantum supremacy": "https://www.nature.com/articles/d41586-019-03213-z",
    "Quantum error correction": "https://quantum-journal.org/papers/q-2021-04-22-433",
    "Quantum teleportation": "https://www.scientificamerican.com/article/quantum-teleportation-approaching-practicality",
    "Quantum machine learning": "https://www.turing.com/kb/what-is-quantum-machine-learning",
    "Adiabatic quantum computing": "https://arxiv.org/abs/quant-ph/0001106",
    "Topological quantum computing": "https://www.microsoft.com/en-us/quantum",
    "Quantum simulation": "https://quantum-journal.org/topics/quantum-simulation",
    "Quantum sensors": "https://www.bnl.gov/newsroom/news.php?a=119992",
    "Quantum metrology": "https://quantum-journal.org/topics/quantum-metrology",
    "Quantum communication networks": "https://www.nature.com/subjects/quantum-communication-networks",
    "Quantum internet": "https://qutech.nl/quantum-internet",
    "Quantum key distribution": "https://www.idquantique.com/quantum-safe-security/solutions/quantum-key-distribution",
    "Quantum random number generation": "https://en.wikipedia.org/wiki/Quantum_random_number_generator",
    "Quantum algorithms": "https://qiskit.org/learn/quantum-algorithms",
    "Quantum programming languages": "https://qiskit.org",
    "Quantum circuit design": "https://quantum-journal.org/papers/q-2020-11-09-362",
    "Quantum hardware": "https://quantum-computing.ibm.com",
    "Quantum software development": "https://azure.microsoft.com/en-us/services/quantum",
    "Quantum artificial intelligence": "https://www.nature.com/articles/s41586-019-1779-7",
    "Quantum neural networks": "https://www.nature.com/articles/s41586-020-03094-1",
    "Quantum image processing": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum games": "https://qutech.nl/research/quantum-internet-applications/games",
    "Quantum chemistry": "https://www.sciencedirect.com/science/article/pii/S0009261418312163",
    "Quantum biology": "https://www.nature.com/articles/s41570-018-0002-1",
    "Quantum finance": "https://quantum-finance.com",
    "Quantum logistics": "https://www.sciencedirect.com/science/article/abs/pii/S0360835216302885",
    "Quantum optimization": "https://www.nature.com/articles/s41534-020-00312-6",
    "Quantum risk analysis": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003231",
    "Quantum entropic uncertainty relations": "https://www.nature.com/articles/ncomms2014",
    "Quantum causality": "https://www.nature.com/articles/nphys3265",
    "Quantum Bayesian inference": "https://www.nature.com/articles/nphys3194",
    "Quantum process tomography": "https://www.sciencedirect.com/science/article/abs/pii/S0009261420307527",
    "Quantum state estimation": "https://www.sciencedirect.com/science/article/abs/pii/S0009261420307527",
    "Quantum state verification": "https://www.nature.com/articles/s41534-020-00303-7",
    "Quantum data compression": "https://www.sciencedirect.com/science/article/abs/pii/S0009261420307527",
    "Quantum error mitigation": "https://quantum-journal.org/papers/q-2020-11-09-362",
    "Quantum circuit compilation": "https://quantum-journal.org/papers/q-2020-11-09-362",
    "Quantum machine learning pipelines": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum benchmarking": "https://www.nature.com/articles/s41534-020-00312-6",
    "Quantum robustness": "https://www.sciencedirect.com/science/article/abs/pii/S0009261420307527",
    "Quantum channel capacities": "https://www.nature.com/articles/s41534-020-00312-6",
    "Quantum coherent control": "https://www.nature.com/articles/s41534-020-00312-6",
    "Quantum precision measurement": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum computing benchmarks": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum computing standards": "https://www.nature.com/articles/s41534-020-00312-6",
    "Quantum computing frameworks": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum machine learning benchmarks": "https://www.nature.com/articles/s41534-020-00312-6",
    "Quantum AI ethics": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum internet protocols": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum communication protocols": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum computing architectures": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum software engineering": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum programming frameworks": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum hardware development": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum computer architectures": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum hardware benchmarks": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum error models": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum noise models": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum machine learning benchmarks": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum computational complexity": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum complexity theory": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum computational models": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum machine learning frameworks": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum computing research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum AI research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum cryptography research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum error correction research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum teleportation research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum communication research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum metrology research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum simulation research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum sensors research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum internet research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum key distribution research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum random number generation research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum hardware research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum software research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum programming research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum machine learning research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum error mitigation research": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum algorithm development": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum circuit optimization": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum computer simulation": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum machine learning applications": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum hardware applications": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum software applications": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum AI applications": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum internet applications": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum communication applications": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255",
    "Quantum computing applications": "https://www.sciencedirect.com/science/article/abs/pii/S0167865521003255"
}

random_searches = random.sample(list(search_terms_to_homepage.keys()), 5)

edge_path = r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"

for search in random_searches:
    try:
        # Open the search page
        subprocess.Popen([edge_path, f"https://www.bing.com/search?q={search}"])
        time.sleep(5)
        # Open the associated homepage
        homepage = search_terms_to_homepage[search]
        subprocess.Popen([edge_path, homepage])
        # time.sleep(60)
    except Exception as e:
        print(f"Failed to open tab for search '{search}': {e}")
